<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="bin\**" />
		<EmbeddedResource Remove="bin\**" />
		<None Remove="bin\**" />
		<Page Remove="bin\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DotNetEnv" Version="3.1.1" />
		<PackageReference Include="EntityFramework" Version="6.5.1" />
		<PackageReference Include="FFMpegCore" Version="5.2.0" />
		<PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
		<PackageReference Include="MaterialDesignColors" Version="5.2.1" />
		<PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
		<PackageReference Include="MaterialDesignThemes.MahApps" Version="5.2.1" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.0-preview.7.25380.108" />
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.5" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
		<PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
	</ItemGroup>

	<ItemGroup>

		<Content Include="Visuals\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>

		<Resource Include="Visuals\Images\Stickers\Figure.png" />

		<Resource Include="Visuals\Images\Stickers\Girl.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>

		<Resource Include="Visuals\Icon\TelIcon.ico" />
		<Resource Include="Visuals\Images\SystemImages\kchau.jpg" />

		<Resource Include="Visuals\Images\UserImages\Minato.jpg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>

		<Resource Include="Visuals\Images\UserImages\WhiteCat.png" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TelegramLib\TelegramLib.csproj" />
		<ProjectReference Include="..\TestThing\TestThing.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Page Update="UserControls\SettingsControls\FoldersPrivacy\IconForFolder.xaml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Page>
	</ItemGroup>

	<ItemGroup>
		<Content Include="LanguageFiles\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<None Update=".env">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
